services:

  postgres:
    image: postgres:17
    container_name: cams-postgres

    environment:
      POSTGRES_DB: consumer_attention_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cams_postgres_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d consumer_attention_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend

    container_name: cams-backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:cams_postgres_password@postgres:5432/consumer_attention_db

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: